import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent";
import { FooterComponent } from "@/components/FooterComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PhishShield",
  description: "Generated by create next app",
  icons: {
    icon: "/shopping.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     {/* Make the entire layout take full height */}
     <div className="flex flex-col min-h-screen">
          <NavbarComponent />
          {/* Main content grows to push the footer down */}
          <main className="flex-grow">{children}</main>
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
